services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  jaeger-tracing:
    image: 'jaegertracing/all-in-one:latest'
    container_name: 'jaeger'
    restart: unless-stopped
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '5775:5775'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true

  elastic:
    image: 'elasticsearch:8.14.1'
    container_name: 'elasticsearch'
    restart: unless-stopped
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: 'logstash:8.14.1'
    container_name: 'logstash'
    restart: unless-stopped
    ports:
      - '5000:5000'
      - '9600:9600'
    volumes:
      - ./src/main/resources/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./src/main/resources:/usr/share/logstash/config
      - ./logs:/usr/share/logstash/logs
      - ./src/main/resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    command: [ "-f", "/usr/share/logstash/config/logstash.conf" ]
    networks:
      - elk-network

  kibana:
    image: 'kibana:8.14.1'
    container_name: 'kibana'
    restart: unless-stopped
#    environment:
    ports:
      - '5601:5601'
    networks:
      - elk-network

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.14.1
    container_name: 'apm-server'
    restart: unless-stopped
    ports:
      - "8200:8200"
    networks:
      - elk-network
    environment:
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - output.elasticsearch.hosts=["http://172.20.0.2:9200"]
      - setup.kibana.host=http://kibana:5601
    volumes:
      - ./src/main/resources/apm-server.yml:/usr/share/apm-server/apm-server.yml

networks:
  elk-network:
    driver: bridge

volumes:
  esdata:
    driver: local
