services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=music'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5431:5432'
  jaeger-tracing:
    image: 'jaegertracing/all-in-one:latest'
    container_name: 'jaeger'
    restart: unless-stopped
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: 'prometheus'
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: 'grafana/grafana:latest'
    container_name: 'grafana'
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
