services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=music'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5431:5432'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  jaeger-tracing:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
#  otel-collector:
#    image: 'otel/opentelemetry-collector'
#    ports:
#      - '4317:4317'
