services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=music'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5431:5432'
  jaeger-tracing:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
