apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-service-deployment
  labels:
    app: artist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artist-service
  template:
    metadata:
      labels:
        app: artist-service
    spec:
      containers:
      - name: artist-service
        image: anishpanthi/artist-service:1.0
        ports:
        - containerPort: 8080
        env:
          - name:
---
apiVersion: v1
kind: Service
metadata:
  name: artist-service
spec:
  selector:
    app: artist-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
