spring:
  application:
    name: artist-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://monorail.proxy.rlwy.net:54849/railway
    username: postgres
    password: iQMNbGTUfPfESkeIXrTwbUyfCXzaoIOe
  security:
    oauth2:
      client:
        provider:
          azure-entra:
            issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0
        registration:
          azure-entra:
            provider: azure-entra
            client-id: 3e9eced8-0b9d-4027-99fe-f986994aba8b
            client-secret: wxM8Q~SVxZnjHk._Xt480jiEf8pLbbKQHVIEcaWw
            client-name: Microsoft Entra ID (Azure AD)
            scope: openid, profile, email, offline_access
            redirect-uri: https://artist-service-production.up.railway.app/login/oauth2/code/azuread
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
        pushgateway:
          base-url: https://railway-prometheus-production-da5c.up.railway.app
          enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin.railway.internal:9411/api/v2/spans
#  otlp:
#    metrics:
#      export:
#        enabled: true
#        url: http://localhost:4317
logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.jdbc: debug
