spring:
  application:
    name: artist-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/music
    username: admin
    password: admin
  docker:
    compose:
      lifecycle-management: start_only
  sql:
    init:
      mode: always

# -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.jdbc: debug
